apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: songs.music.sportshead.dev
spec:
  group: music.sportshead.dev
  scope: Namespaced
  names:
    plural: songs
    singular: song
    kind: Song
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                title:
                  type: string
                artist:
                  type: string
                rating:
                  type: integer
                  enum: [1, 2, 3, 4, 5]
                genres:
                  type: array
                  items:
                    type: string
              required:
                - title
                - artist
